require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SelftestsController do

  # This should return the minimal set of attributes required to create a valid
  # Selftest. As you add validations to Selftest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SelftestsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all selftests as @selftests" do
      selftest = Selftest.create! valid_attributes
      get :index, {}, valid_session
      assigns(:selftests).should eq([selftest])
    end
  end

  describe "GET show" do
    it "assigns the requested selftest as @selftest" do
      selftest = Selftest.create! valid_attributes
      get :show, {:id => selftest.to_param}, valid_session
      assigns(:selftest).should eq(selftest)
    end
  end

  describe "GET new" do
    it "assigns a new selftest as @selftest" do
      get :new, {}, valid_session
      assigns(:selftest).should be_a_new(Selftest)
    end
  end

  describe "GET edit" do
    it "assigns the requested selftest as @selftest" do
      selftest = Selftest.create! valid_attributes
      get :edit, {:id => selftest.to_param}, valid_session
      assigns(:selftest).should eq(selftest)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Selftest" do
        expect {
          post :create, {:selftest => valid_attributes}, valid_session
        }.to change(Selftest, :count).by(1)
      end

      it "assigns a newly created selftest as @selftest" do
        post :create, {:selftest => valid_attributes}, valid_session
        assigns(:selftest).should be_a(Selftest)
        assigns(:selftest).should be_persisted
      end

      it "redirects to the created selftest" do
        post :create, {:selftest => valid_attributes}, valid_session
        response.should redirect_to(Selftest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved selftest as @selftest" do
        # Trigger the behavior that occurs when invalid params are submitted
        Selftest.any_instance.stub(:save).and_return(false)
        post :create, {:selftest => { "name" => "invalid value" }}, valid_session
        assigns(:selftest).should be_a_new(Selftest)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Selftest.any_instance.stub(:save).and_return(false)
        post :create, {:selftest => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested selftest" do
        selftest = Selftest.create! valid_attributes
        # Assuming there are no other selftests in the database, this
        # specifies that the Selftest created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Selftest.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => selftest.to_param, :selftest => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested selftest as @selftest" do
        selftest = Selftest.create! valid_attributes
        put :update, {:id => selftest.to_param, :selftest => valid_attributes}, valid_session
        assigns(:selftest).should eq(selftest)
      end

      it "redirects to the selftest" do
        selftest = Selftest.create! valid_attributes
        put :update, {:id => selftest.to_param, :selftest => valid_attributes}, valid_session
        response.should redirect_to(selftest)
      end
    end

    describe "with invalid params" do
      it "assigns the selftest as @selftest" do
        selftest = Selftest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Selftest.any_instance.stub(:save).and_return(false)
        put :update, {:id => selftest.to_param, :selftest => { "name" => "invalid value" }}, valid_session
        assigns(:selftest).should eq(selftest)
      end

      it "re-renders the 'edit' template" do
        selftest = Selftest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Selftest.any_instance.stub(:save).and_return(false)
        put :update, {:id => selftest.to_param, :selftest => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested selftest" do
      selftest = Selftest.create! valid_attributes
      expect {
        delete :destroy, {:id => selftest.to_param}, valid_session
      }.to change(Selftest, :count).by(-1)
    end

    it "redirects to the selftests list" do
      selftest = Selftest.create! valid_attributes
      delete :destroy, {:id => selftest.to_param}, valid_session
      response.should redirect_to(selftests_url)
    end
  end

end
